import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HandlerDisplay from '../components/HandlerDisplay';

export async function getServerSideProps() {
  const { initialData } = await fetch("http://localhost:8000/handler-initial-data").then(x => x.json());
  return {
    props: {
      data: initialData ?? null,
    }
  }
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <HandlerDisplay data={data} />
      </main>
    </div>
  )
}
